name = "bid8iran"
main = "index.js"
compatibility_date = "2025-11-09"
workers_dev = true
preview_urls = true
# logpush job is setup to capture from envs ending: log, pro, or one
logpush = false
# use node_compat or custom build
# node_compat = true
send_metrics = false
minify = false

[vars]
UUID = "59286eec-5ba8-42d5-90f1-09e2ba0a8d62"
PROXYIP = "nima.nscl.ir"

# [build]
# command = "npm run deploy"

# [[rules]]
# type = "ESModule"
# globs = ["**/*.js"]
